//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapperTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpEntityChangeSets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbpEntityChangeSets()
        {
            this.AbpEntityChanges = new HashSet<AbpEntityChanges>();
        }
    
        public long Id { get; set; }
        public string BrowserInfo { get; set; }
        public string ClientIpAddress { get; set; }
        public string ClientName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string ExtensionData { get; set; }
        public Nullable<int> ImpersonatorTenantId { get; set; }
        public Nullable<long> ImpersonatorUserId { get; set; }
        public string Reason { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<long> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbpEntityChanges> AbpEntityChanges { get; set; }
    }
}
