--2.隔离级别的分类
--（1）未提交读 （READ UNCOMMITTED）

--（2）已提交读（READ COMMITTED）（默认值）

--（3）可重复读（REPEATABLE READ）

--（4）可序列化（SERIALIZABLE）

--（5）快照（SNAPSHOT）

--（6）已经提交读快照（READ_COMMITTED_SNAPSHOT）

--BEGIN TRANSACTION

--	--未提交读
--	SET TRAN ISOLATION LEVEL READ UNCOMMITTED

--	SELECT * FROM Product--与事务A各阶段显示相同
--	WHERE Id = 1 

--COMMIT TRANSACTION

BEGIN TRANSACTION

	--已提交读【默认级别】
	SET TRAN ISOLATION LEVEL READ COMMITTED

	--读取获取共享锁  
	--当查询信息具有排他锁 需等待至排他锁结束
	SELECT * FROM Product--与事务A各阶段显示相同
	WHERE Id = 1 

COMMIT TRANSACTION