//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTable
    {
        public int a_Id { get; set; }
        public string a_Title { get; set; }
        public Nullable<int> a_Type { get; set; }
        public string a_Picture { get; set; }
        public string a_Author { get; set; }
        public string a_Description { get; set; }
        public string a_KeyWord { get; set; }
        public Nullable<int> a_Seqence { get; set; }
        public string a_Content { get; set; }
        public Nullable<int> a_Hits { get; set; }
        public Nullable<int> a_Thumbs { get; set; }
        public Nullable<int> a_Status { get; set; }
        public Nullable<bool> a_UrlStatus { get; set; }
        public string a_Url { get; set; }
        public Nullable<System.DateTime> a_AddTime { get; set; }
    }
}
