//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTable
    {
        public int a_Id { get; set; }
        public Nullable<System.DateTime> a_AttendanceDate { get; set; }
        public Nullable<int> a_ClassTimeId { get; set; }
        public Nullable<int> a_CompusId { get; set; }
        public Nullable<int> a_ClassId { get; set; }
        public Nullable<int> a_ClassRoomId { get; set; }
        public Nullable<int> a_TeacherId { get; set; }
        public Nullable<int> a_StudentId { get; set; }
        public Nullable<int> a_StudentType { get; set; }
        public Nullable<int> a_AttendanceStatus { get; set; }
        public string a_Remark { get; set; }
        public Nullable<System.DateTime> a_AddTime { get; set; }
        public Nullable<int> a_RegistrarId { get; set; }
        public Nullable<bool> a_CheckStatus { get; set; }
        public Nullable<System.DateTime> a_CheckTime { get; set; }
        public Nullable<int> a_Week { get; set; }
        public Nullable<System.TimeSpan> a_StartTime { get; set; }
        public Nullable<System.TimeSpan> a_EndTime { get; set; }
        public Nullable<int> a_NeedArrive { get; set; }
        public Nullable<int> a_ActualArrive { get; set; }
        public Nullable<int> a_LeaveNumber { get; set; }
        public Nullable<int> a_AbsenceNumber { get; set; }
        public Nullable<int> a_StudentCourseId { get; set; }
        public Nullable<int> a_Status { get; set; }
        public string a_ClassTeacherId { get; set; }
        public Nullable<int> a_OldAttendanceStatus { get; set; }
        public Nullable<int> a_DataId { get; set; }
        public Nullable<int> a_SignUpId { get; set; }
        public Nullable<int> a_ClassHours { get; set; }
    }
}
