//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttentionTable
    {
        public int a_Id { get; set; }
        public int a_User_id { get; set; }
        public int a_Attention_id { get; set; }
        public bool a_Is_new { get; set; }
        public int a_Status { get; set; }
        public System.DateTime a_Created_at { get; set; }
    }
}
