//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditionRecordTable
    {
        public int ar_Id { get; set; }
        public Nullable<int> ar_ConsultId { get; set; }
        public Nullable<int> ar_StudentId { get; set; }
        public Nullable<int> ar_Type { get; set; }
        public int ar_DataId { get; set; }
        public string ar_DataName { get; set; }
        public Nullable<int> ar_CompusId { get; set; }
        public Nullable<int> ar_CourseId { get; set; }
        public Nullable<int> ar_TeacherId { get; set; }
        public Nullable<int> ar_ClassRoomId { get; set; }
        public Nullable<System.DateTime> ar_Date { get; set; }
        public Nullable<System.TimeSpan> ar_StartTime { get; set; }
        public Nullable<System.TimeSpan> ar_EndTime { get; set; }
        public string ar_FeedBack { get; set; }
        public string ar_Remark { get; set; }
        public Nullable<int> ar_Status { get; set; }
        public Nullable<int> ar_StaffId { get; set; }
        public string ar_StaffName { get; set; }
        public Nullable<System.DateTime> ar_AddTime { get; set; }
    }
}
