//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceRecordTable
    {
        public int br_Id { get; set; }
        public Nullable<int> br_StudentId { get; set; }
        public Nullable<int> br_UserId { get; set; }
        public string br_OrderId { get; set; }
        public Nullable<decimal> br_Money { get; set; }
        public string br_Remark { get; set; }
        public Nullable<int> br_Type { get; set; }
        public Nullable<int> br_FromUserId { get; set; }
        public Nullable<int> br_Channel { get; set; }
        public Nullable<System.DateTime> br_AddTime { get; set; }
        public string br_Flag { get; set; }
    }
}
