//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCardTransferTable
    {
        public int bt_Id { get; set; }
        public string bt_OrderId { get; set; }
        public Nullable<int> bt_UserId { get; set; }
        public string bt_Picture { get; set; }
        public string bt_Remark { get; set; }
        public Nullable<int> bt_Status { get; set; }
        public Nullable<System.DateTime> bt_AddTime { get; set; }
    }
}
