//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerTable
    {
        public int b_Id { get; set; }
        public Nullable<int> b_Type { get; set; }
        public string b_Title { get; set; }
        public string b_Picture { get; set; }
        public string b_Author { get; set; }
        public string b_KeyWord { get; set; }
        public string b_Description { get; set; }
        public string b_Content { get; set; }
        public Nullable<int> b_Hits { get; set; }
        public Nullable<bool> b_UrlStatus { get; set; }
        public string b_Url { get; set; }
        public Nullable<int> b_Sequence { get; set; }
        public Nullable<int> b_Status { get; set; }
        public Nullable<System.DateTime> b_AddTime { get; set; }
    }
}
