//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeClassTable
    {
        public int cc_Id { get; set; }
        public Nullable<int> cc_StudentId { get; set; }
        public Nullable<int> cc_CampusId { get; set; }
        public Nullable<int> cc_ClassId { get; set; }
        public string cc_OrderId { get; set; }
        public Nullable<int> cc_SignUpId { get; set; }
        public Nullable<int> cc_StudentClassId { get; set; }
        public Nullable<int> cc_StudentCampusId { get; set; }
        public Nullable<int> cc_Amount { get; set; }
        public Nullable<int> cc_LeftAmount { get; set; }
        public Nullable<decimal> cc_LeftTuition { get; set; }
        public Nullable<decimal> cc_PayTuition { get; set; }
        public Nullable<int> cc_StaffId { get; set; }
        public Nullable<int> cc_Status { get; set; }
        public Nullable<System.DateTime> cc_CheckTime { get; set; }
        public Nullable<int> cc_CheckStaffId { get; set; }
        public Nullable<System.DateTime> cc_AddTime { get; set; }
        public Nullable<int> cc_RefundType { get; set; }
    }
}
