//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Time_TeacherTable
    {
        public int ctt_id { get; set; }
        public Nullable<int> ctt_Class_time_id { get; set; }
        public Nullable<int> ctt_Teacher_id { get; set; }
        public Nullable<int> ctt_Status { get; set; }
        public Nullable<System.DateTime> ctt_Created_at { get; set; }
    }
}
