//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTable
    {
        public int c_Id { get; set; }
        public int c_CompusId { get; set; }
        public int c_CourseId { get; set; }
        public Nullable<int> c_CourseType { get; set; }
        public Nullable<int> c_ChargeType { get; set; }
        public Nullable<int> c_Course_price_id { get; set; }
        public Nullable<int> c_ClassRoomId { get; set; }
        public Nullable<int> c_TeacherId { get; set; }
        public string c_Name { get; set; }
        public Nullable<int> c_LimitAmount { get; set; }
        public Nullable<int> c_Amount { get; set; }
        public Nullable<bool> c_RecruitStatus { get; set; }
        public Nullable<System.DateTime> c_StartClassTime { get; set; }
        public Nullable<System.DateTime> c_EndClassTime { get; set; }
        public Nullable<bool> c_UnifyClose { get; set; }
        public Nullable<bool> c_IsEndClass { get; set; }
        public Nullable<int> c_Status { get; set; }
        public string c_Remark { get; set; }
        public Nullable<int> c_Creator { get; set; }
        public double c_ClassHoursStudent { get; set; }
        public double c_ClassHoursTeacher { get; set; }
        public Nullable<System.DateTime> c_AddTime { get; set; }
    }
}
