//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoomTable
    {
        public int c_Id { get; set; }
        public int c_CompusId { get; set; }
        public string c_Name { get; set; }
        public Nullable<bool> c_Status { get; set; }
        public Nullable<System.DateTime> c_AddTime { get; set; }
    }
}
