//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRelationTable
    {
        public int cr_Id { get; set; }
        public Nullable<int> cr_UserId { get; set; }
        public Nullable<int> cr_Identity { get; set; }
        public Nullable<int> cr_ClassId { get; set; }
        public Nullable<System.DateTime> cr_AddTime { get; set; }
    }
}
