//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_TimeTable
    {
        public int ct_id { get; set; }
        public int ct_Class_id { get; set; }
        public Nullable<int> ct_Room_id { get; set; }
        public int ct_Week { get; set; }
        public System.TimeSpan ct_Start_time { get; set; }
        public System.TimeSpan ct_End_time { get; set; }
        public int ct_Status { get; set; }
        public System.DateTime ct_Created_at { get; set; }
    }
}
