//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectTable
    {
        public int co_Id { get; set; }
        public int co_StaffId { get; set; }
        public int co_uId { get; set; }
        public Nullable<int> co_CourseId { get; set; }
        public int co_Status { get; set; }
        public System.DateTime co_Created_at { get; set; }
    }
}
