//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompusAreaTable
    {
        public int a_Id { get; set; }
        public string a_Name { get; set; }
        public Nullable<int> a_AddStaffId { get; set; }
        public string a_AddStaffName { get; set; }
        public Nullable<int> a_Status { get; set; }
        public Nullable<System.DateTime> a_AddTime { get; set; }
    }
}
