//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompusTable
    {
        public int c_Id { get; set; }
        public Nullable<int> c_Sequence { get; set; }
        public Nullable<int> c_Area { get; set; }
        public Nullable<int> c_Type { get; set; }
        public string c_Compus_Name { get; set; }
        public string c_Province { get; set; }
        public string c_Province_code { get; set; }
        public string c_City { get; set; }
        public string c_City_code { get; set; }
        public string c_District { get; set; }
        public string c_District_code { get; set; }
        public string c_DetailAddr { get; set; }
        public Nullable<double> c_Lng { get; set; }
        public Nullable<double> c_Lat { get; set; }
        public string c_Mobile1 { get; set; }
        public string c_Mobile2 { get; set; }
        public string c_Picture { get; set; }
        public string c_Carousel { get; set; }
        public string c_Description { get; set; }
        public Nullable<int> c_Status { get; set; }
        public Nullable<System.DateTime> c_AddTime { get; set; }
    }
}
