//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultFollowTable
    {
        public int cf_Id { get; set; }
        public Nullable<int> cf_ConsultId { get; set; }
        public string cf_Mobile { get; set; }
        public string cf_Type { get; set; }
        public string cf_IntentionContent { get; set; }
        public Nullable<int> cf_FollowType { get; set; }
        public Nullable<System.DateTime> cf_FollowTime { get; set; }
        public Nullable<int> cf_FollowStaffId { get; set; }
        public Nullable<System.DateTime> cf_AddTime { get; set; }
        public Nullable<bool> cf_IsNoticed { get; set; }
    }
}
