//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultTable
    {
        public int c_Id { get; set; }
        public Nullable<int> c_StudentId { get; set; }
        public Nullable<int> c_CreatorId { get; set; }
        public Nullable<int> c_Channel { get; set; }
        public string c_Concern { get; set; }
        public string c_ConcernOther { get; set; }
        public string c_Relation { get; set; }
        public string c_RelationOther { get; set; }
        public string c_ConsultWay { get; set; }
        public Nullable<int> c_Intention { get; set; }
        public Nullable<int> c_CompusId { get; set; }
        public Nullable<int> c_LeafLetStaffId { get; set; }
        public Nullable<int> c_SellerStaffId { get; set; }
        public Nullable<int> c_CourseId_1 { get; set; }
        public Nullable<int> c_CourseId_2 { get; set; }
        public Nullable<int> c_CourseId_3 { get; set; }
        public Nullable<int> c_Status { get; set; }
        public Nullable<bool> c_IsInPool { get; set; }
        public Nullable<System.DateTime> c_ReceiveTime { get; set; }
        public Nullable<System.DateTime> c_UpdateTime { get; set; }
        public Nullable<System.DateTime> c_FollowUpTime { get; set; }
        public Nullable<System.DateTime> c_AddTime { get; set; }
    }
}
