//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursewareDecipheringTable
    {
        public int cd_Id { get; set; }
        public Nullable<int> cd_Cid { get; set; }
        public Nullable<System.DateTime> cd_deciphering_time { get; set; }
        public int cd_Status { get; set; }
        public System.DateTime cd_Create_at { get; set; }
    }
}
