//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursePriceTable
    {
        public int cp_Id { get; set; }
        public int cp_CourseId { get; set; }
        public int cp_Type { get; set; }
        public string cp_Name { get; set; }
        public string cp_Remark { get; set; }
        public decimal cp_Price { get; set; }
        public Nullable<int> cp_ClassHours { get; set; }
        public Nullable<int> cp_Status { get; set; }
        public Nullable<System.DateTime> cp_AddTime { get; set; }
    }
}
