//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courseware_OpinionTable
    {
        public int o_Id { get; set; }
        public string o_Cause { get; set; }
        public string o_Picture { get; set; }
        public Nullable<int> o_State { get; set; }
        public Nullable<System.DateTime> o_AddTime { get; set; }
        public Nullable<int> c_Id { get; set; }
        public Nullable<int> c_StaffId { get; set; }
        public Nullable<int> c_UserId { get; set; }
        public Nullable<int> o_processState { get; set; }
        public string o_Title { get; set; }
    }
}
