//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseActiveTable
    {
        public int ca_Id { get; set; }
        public string ca_OrderId { get; set; }
        public string ca_ActiveCode { get; set; }
        public Nullable<bool> ca_ActiveStatus { get; set; }
        public Nullable<System.DateTime> ca_ActiveTime { get; set; }
        public Nullable<int> ca_UserId { get; set; }
        public Nullable<int> ca_StaffId { get; set; }
        public Nullable<int> ca_ConsultId { get; set; }
        public Nullable<System.DateTime> ca_AddTime { get; set; }
    }
}
