//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursewareTable
    {
        public int c_Id { get; set; }
        public string c_Title { get; set; }
        public Nullable<int> c_Type { get; set; }
        public string c_Picture { get; set; }
        public string c_KnowledgePoint { get; set; }
        public string c_Procedure { get; set; }
        public string c_Adjunct { get; set; }
        public string c_Adjunct_id { get; set; }
        public Nullable<int> c_AuditState { get; set; }
        public int c_State { get; set; }
        public System.DateTime c_AddTime { get; set; }
        public Nullable<int> c_StaffId { get; set; }
        public Nullable<int> c_Score { get; set; }
        public string c_Stuff { get; set; }
        public string c_Video { get; set; }
        public string c_Remarks { get; set; }
        public int c_DownloadsCount { get; set; }
    }
}
