//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendApplyTable
    {
        public int fa_Id { get; set; }
        public Nullable<int> fa_UserId { get; set; }
        public Nullable<int> fa_FriendId { get; set; }
        public Nullable<int> fa_Status { get; set; }
        public string fa_Remark { get; set; }
        public Nullable<System.DateTime> fa_UpdateTime { get; set; }
        public Nullable<System.DateTime> fa_AddTime { get; set; }
    }
}
