//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTable
    {
        public int j_Id { get; set; }
        public string j_Name { get; set; }
        public Nullable<int> j_DepartmentId { get; set; }
        public Nullable<int> j_Status { get; set; }
        public Nullable<int> j_AddStaffId { get; set; }
        public Nullable<System.DateTime> j_AddTime { get; set; }
    }
}
