//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRecordTable
    {
        public int lr_Id { get; set; }
        public int lr_StudentId { get; set; }
        public int lr_CampusId { get; set; }
        public int lr_ClassId { get; set; }
        public System.DateTime lr_StartTime { get; set; }
        public System.DateTime lr_EndTime { get; set; }
        public Nullable<int> lr_Amount { get; set; }
        public int lr_AddStaff { get; set; }
        public string lr_Remark { get; set; }
        public Nullable<int> lr_Status { get; set; }
        public Nullable<System.DateTime> lr_AddTime { get; set; }
        public Nullable<bool> lr_HasMakeUp { get; set; }
        public Nullable<System.DateTime> lr_MakeUp_StartTime { get; set; }
        public Nullable<System.DateTime> lr_MakeUp_EndTime { get; set; }
        public Nullable<int> lr_MakeUp_ClassId { get; set; }
        public Nullable<System.DateTime> lr_OldEndTime { get; set; }
        public Nullable<int> lr_DataId { get; set; }
    }
}
