//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakeUpClassTable
    {
        public int mc_Id { get; set; }
        public Nullable<int> mc_Type { get; set; }
        public int mc_CampusId { get; set; }
        public int mc_StudentId { get; set; }
        public int mc_ClassId { get; set; }
        public System.DateTime mc_StartTime { get; set; }
        public System.DateTime mc_EndTime { get; set; }
        public int mc_Amount { get; set; }
        public Nullable<int> mc_AddStaff { get; set; }
        public Nullable<System.DateTime> mc_AddTime { get; set; }
        public Nullable<int> mc_Status { get; set; }
        public int mc_DataId { get; set; }
        public Nullable<int> mc_LeaveRecordId { get; set; }
        public int mc_StudentClassId { get; set; }
    }
}
