//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOrderTable
    {
        public int mo_Id { get; set; }
        public Nullable<int> mo_Type { get; set; }
        public string mo_OrderId { get; set; }
        public string mo_ChildOrderId { get; set; }
        public Nullable<int> mo_MaterialId { get; set; }
        public string mo_MaterialName { get; set; }
        public Nullable<decimal> mo_MaterialMoney { get; set; }
        public Nullable<System.DateTime> mo_AddTime { get; set; }
    }
}
