//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTable
    {
        public int m_Id { get; set; }
        public Nullable<int> m_Type { get; set; }
        public string m_Name { get; set; }
        public Nullable<int> m_CourseType { get; set; }
        public Nullable<decimal> m_Money { get; set; }
        public Nullable<int> m_Status { get; set; }
        public Nullable<System.DateTime> m_AddTime { get; set; }
        public string m_ImportNo { get; set; }
    }
}
