//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyTable
    {
        public int n_Id { get; set; }
        public int n_Staff_id { get; set; }
        public int n_Sequence { get; set; }
        public string n_Title { get; set; }
        public string n_Content { get; set; }
        public int n_Messagetype { get; set; }
        public int n_Status { get; set; }
        public System.DateTime n_Created_at { get; set; }
    }
}
