//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int o_Id { get; set; }
        public string o_OrderId { get; set; }
        public Nullable<int> o_UserId { get; set; }
        public Nullable<int> o_Type { get; set; }
        public string o_OrderName { get; set; }
        public Nullable<decimal> o_Money { get; set; }
        public Nullable<int> o_Status { get; set; }
        public Nullable<int> o_OldStatus { get; set; }
        public Nullable<bool> o_IsEvaluate { get; set; }
        public Nullable<System.DateTime> o_AddTime { get; set; }
    }
}
