//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUserActiveTable
    {
        public int ua_Id { get; set; }
        public int ua_uId { get; set; }
        public Nullable<int> ua_Staff_id { get; set; }
        public Nullable<System.DateTime> ua_StartValidity { get; set; }
        public Nullable<System.DateTime> ua_EndValidity { get; set; }
        public string ua_Voucher_url { get; set; }
        public Nullable<System.DateTime> ua_Auditor { get; set; }
        public string ua_Content { get; set; }
        public int ua_Status { get; set; }
        public System.DateTime ua_Create_at { get; set; }
    }
}
