//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderTable
    {
        public int r_Id { get; set; }
        public Nullable<int> r_nId { get; set; }
        public int r_Readstatus { get; set; }
        public int r_uId { get; set; }
        public int r_Staff_id { get; set; }
        public System.DateTime r_Create_at { get; set; }
        public int r_Status { get; set; }
    }
}
