//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitAddressTable
    {
        public int ra_Id { get; set; }
        public Nullable<int> ra_CompusId { get; set; }
        public string ra_Name { get; set; }
        public string ra_Address { get; set; }
        public string ra_Mobile { get; set; }
        public Nullable<int> ra_Status { get; set; }
        public Nullable<int> ra_Sequence { get; set; }
        public Nullable<System.DateTime> ra_AddTime { get; set; }
    }
}
