//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundTable
    {
        public int r_Id { get; set; }
        public string r_OrderId { get; set; }
        public string r_ChildOrderId { get; set; }
        public int r_Type { get; set; }
        public string r_Body { get; set; }
        public int r_StudentId { get; set; }
        public int r_SignUpId { get; set; }
        public Nullable<int> r_CampusId { get; set; }
        public Nullable<int> r_ClassId { get; set; }
        public int r_SellerId { get; set; }
        public decimal r_Money { get; set; }
        public string r_Remark { get; set; }
        public Nullable<int> r_Status { get; set; }
        public Nullable<int> r_StaffId { get; set; }
        public Nullable<int> r_AuditStaffId { get; set; }
        public Nullable<System.DateTime> r_AuditTime { get; set; }
        public string r_AuditRemark { get; set; }
        public Nullable<System.DateTime> r_AddTime { get; set; }
        public int r_RefundWay { get; set; }
    }
}
