//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundSnapShot
    {
        public int rs_Id { get; set; }
        public int rs_RefundId { get; set; }
        public int rs_SignUpId { get; set; }
        public int rs_Type { get; set; }
        public int rs_DataId { get; set; }
        public int rs_Value { get; set; }
        public Nullable<System.DateTime> rs_AddTime { get; set; }
        public Nullable<bool> rs_Status { get; set; }
    }
}
