//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepaymentTable
    {
        public int rt_Id { get; set; }
        public string rt_OrderId { get; set; }
        public Nullable<int> rt_Type { get; set; }
        public Nullable<int> rt_CampusId { get; set; }
        public Nullable<decimal> rt_OriginalMoney { get; set; }
        public decimal rt_Money { get; set; }
        public string rt_PayWay { get; set; }
        public string rt_Certificate { get; set; }
        public Nullable<int> rt_Status { get; set; }
        public string rt_Remark { get; set; }
        public int rt_AddStaffId { get; set; }
        public Nullable<System.DateTime> rt_AddTime { get; set; }
        public Nullable<int> rt_AuditStaffId { get; set; }
        public Nullable<System.DateTime> rt_AuditTime { get; set; }
        public string rt_AuditRemark { get; set; }
        public Nullable<bool> rt_IsError { get; set; }
        public Nullable<decimal> rt_ErrorMoney { get; set; }
    }
}
