//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUpOrder_Edit_Table
    {
        public string se_ImportNo { get; set; }
        public string se_OrderId { get; set; }
        public string se_ChildOrderId { get; set; }
        public string se_Remark { get; set; }
        public string se_PayWay { get; set; }
        public Nullable<int> se_SellerId { get; set; }
        public Nullable<int> se_StaffId { get; set; }
        public Nullable<int> se_Status { get; set; }
        public Nullable<System.DateTime> se_AddTime { get; set; }
        public int se_Id { get; set; }
    }
}
