//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUpOrderOffTable
    {
        public int sf_Id { get; set; }
        public string sf_OrderId { get; set; }
        public string sf_ChildOrderId { get; set; }
        public Nullable<int> sf_Type { get; set; }
        public Nullable<decimal> sf_Value { get; set; }
        public Nullable<decimal> sf_Money { get; set; }
        public Nullable<int> sf_Status { get; set; }
        public Nullable<System.DateTime> sf_AddTime { get; set; }
    }
}
