//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffMsgTable
    {
        public int sm_Id { get; set; }
        public Nullable<int> sm_Type { get; set; }
        public string sm_Title { get; set; }
        public string sm_Content { get; set; }
        public Nullable<int> sm_Status { get; set; }
        public string sm_CompusId { get; set; }
        public string sm_RoleId { get; set; }
        public Nullable<int> sm_AddStaff { get; set; }
        public Nullable<System.DateTime> sm_AddTime { get; set; }
    }
}
