//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffActiveTable
    {
        public int sa_Id { get; set; }
        public string sa_Avatar { get; set; }
        public string sa_Name { get; set; }
        public string sa_Sex { get; set; }
        public string sa_Mobile { get; set; }
        public string sa_Email { get; set; }
        public Nullable<System.DateTime> sa_BirthDay { get; set; }
        public Nullable<int> sa_Role { get; set; }
        public string sa_ActiveCode { get; set; }
        public Nullable<bool> sa_ActiveStatus { get; set; }
        public Nullable<System.DateTime> sa_ActiveTime { get; set; }
        public Nullable<int> sa_StaffId { get; set; }
        public string sa_ImportNo { get; set; }
        public Nullable<int> sa_Status { get; set; }
        public Nullable<System.DateTime> sa_AddTime { get; set; }
        public Nullable<int> sa_Marry { get; set; }
        public string sa_NativePlace { get; set; }
        public string sa_HouseHoldType { get; set; }
        public string sa_IdCard { get; set; }
        public string sa_IdCardAddr { get; set; }
        public string sa_Education { get; set; }
        public string sa_School { get; set; }
        public string sa_Major { get; set; }
        public string sa_Linker { get; set; }
        public string sa_LinkerMob { get; set; }
        public string sa_Bank_ICBC { get; set; }
        public string sa_Bank_ABC { get; set; }
        public string sa_IdCard_Front { get; set; }
        public string sa_IdCard_Back { get; set; }
        public string sa_Resume { get; set; }
        public string sa_LaborContract { get; set; }
        public Nullable<System.DateTime> sa_LaborContract_Start { get; set; }
        public Nullable<System.DateTime> sa_LaborContract_End { get; set; }
        public Nullable<int> sa_LaborContract_Count { get; set; }
        public Nullable<int> sa_DepartmentId { get; set; }
        public Nullable<int> sa_JobId { get; set; }
        public string sa_JobGrade { get; set; }
        public Nullable<System.DateTime> sa_HireDate { get; set; }
        public Nullable<int> sa_WorkAge { get; set; }
        public string sa_Insurer { get; set; }
        public Nullable<bool> sa_HasQC { get; set; }
        public string sa_WorkExperience { get; set; }
        public string sa_DirectSuperior { get; set; }
    }
}
