//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffCompusTable
    {
        public int sc_Id { get; set; }
        public Nullable<int> sc_StaffId { get; set; }
        public Nullable<int> sc_CompusId { get; set; }
        public Nullable<int> sc_ActiveId { get; set; }
        public string sc_ImportNo { get; set; }
        public System.DateTime sc_AddTime { get; set; }
    }
}
