//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTable
    {
        public int s_Id { get; set; }
        public Nullable<int> s_Role { get; set; }
        public string s_Open_id { get; set; }
        public string s_Account { get; set; }
        public string s_Password { get; set; }
        public string s_Name { get; set; }
        public string s_NickName { get; set; }
        public string s_Avatar { get; set; }
        public string s_Sex { get; set; }
        public Nullable<System.DateTime> s_BirthDay { get; set; }
        public string s_Email { get; set; }
        public string s_Mobile { get; set; }
        public bool s_IsActive { get; set; }
        public bool s_IsTeacher { get; set; }
        public int s_Status { get; set; }
        public System.DateTime s_AddTime { get; set; }
        public Nullable<int> s_Marry { get; set; }
        public string s_NativePlace { get; set; }
        public string s_HouseHoldType { get; set; }
        public string s_IdCard { get; set; }
        public string s_IdCardAddr { get; set; }
        public string s_Education { get; set; }
        public string s_Major { get; set; }
        public string s_School { get; set; }
        public string s_Linker { get; set; }
        public string s_LinkerMob { get; set; }
        public string s_Bank_ICBC { get; set; }
        public string s_Bank_ABC { get; set; }
        public string s_IdCard_Front { get; set; }
        public string s_IdCard_Back { get; set; }
        public string s_Resume { get; set; }
        public string s_LaborContract { get; set; }
        public Nullable<System.DateTime> s_LaborContract_Start { get; set; }
        public Nullable<System.DateTime> s_LaborContract_End { get; set; }
        public Nullable<int> s_LaborContract_Count { get; set; }
        public Nullable<int> s_DepartmentId { get; set; }
        public Nullable<int> s_JobId { get; set; }
        public string s_JobGrade { get; set; }
        public Nullable<System.DateTime> s_HireDate { get; set; }
        public Nullable<int> s_WorkAge { get; set; }
        public string s_Insurer { get; set; }
        public Nullable<bool> s_HasQC { get; set; }
        public string s_WorkExperience { get; set; }
        public string s_DirectSuperior { get; set; }
    }
}
