//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseImport
    {
        public string sci_Name { get; set; }
        public string sci_Mobile { get; set; }
        public string sci_Sex { get; set; }
        public Nullable<System.DateTime> sci_BirthDay { get; set; }
        public string sci_LinkerName { get; set; }
        public string sci_LinkerMobile { get; set; }
        public string sci_Email { get; set; }
        public System.DateTime sci_StartDate { get; set; }
        public Nullable<System.DateTime> sci_EndDate { get; set; }
        public int sci_Amount { get; set; }
        public int sci_ClassId { get; set; }
        public string sci_Import { get; set; }
        public int sci_StaffId { get; set; }
        public Nullable<System.DateTime> sci_AddTime { get; set; }
        public Nullable<int> sci_Status { get; set; }
        public string sci_ErrorDesc { get; set; }
        public int sci_Id { get; set; }
        public string sci_OrderId { get; set; }
        public Nullable<int> sci_StudentId { get; set; }
    }
}
