//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseTable
    {
        public int sc_Id { get; set; }
        public Nullable<int> sc_UserId { get; set; }
        public int sc_StudentId { get; set; }
        public string sc_OrderId { get; set; }
        public int sc_ClassId { get; set; }
        public Nullable<System.DateTime> sc_ClassStartDate { get; set; }
        public Nullable<System.DateTime> sc_ClassEndDate { get; set; }
        public Nullable<System.DateTime> sc_ValidDate { get; set; }
        public Nullable<int> sc_Amount { get; set; }
        public string sc_Remark { get; set; }
        public Nullable<int> sc_Status { get; set; }
        public Nullable<System.DateTime> sc_AddTime { get; set; }
        public Nullable<int> sc_CampusId { get; set; }
        public Nullable<int> sc_ClassPriceType { get; set; }
        public Nullable<decimal> sc_PerClassPrice { get; set; }
    }
}
