//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int s_Id { get; set; }
        public Nullable<int> s_UserId { get; set; }
        public string s_Avatar { get; set; }
        public string s_Name { get; set; }
        public string s_Sex { get; set; }
        public Nullable<System.DateTime> s_BirthDay { get; set; }
        public string s_School { get; set; }
        public string s_Mobile { get; set; }
        public string s_LinkerName { get; set; }
        public string s_LinkerMobile { get; set; }
        public string s_Email { get; set; }
        public string s_Address { get; set; }
        public string s_DetailAddress { get; set; }
        public Nullable<decimal> s_BalanceMoney { get; set; }
        public Nullable<System.DateTime> s_AddTime { get; set; }
        public Nullable<int> s_Status { get; set; }
        public Nullable<int> s_Type { get; set; }
    }
}
