//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuspendTable
    {
        public int s_Id { get; set; }
        public int s_Type { get; set; }
        public Nullable<int> s_Status { get; set; }
        public Nullable<System.DateTime> s_Date { get; set; }
        public int s_DataId { get; set; }
        public Nullable<int> s_CampusId { get; set; }
        public Nullable<int> s_ClassId { get; set; }
        public Nullable<int> s_StudentId { get; set; }
        public string s_Teacher { get; set; }
        public Nullable<int> s_RoomId { get; set; }
        public Nullable<System.TimeSpan> s_Start_time { get; set; }
        public Nullable<System.TimeSpan> s_End_time { get; set; }
        public int s_StaffId { get; set; }
        public string s_Remark { get; set; }
        public Nullable<System.DateTime> s_AddTime { get; set; }
        public Nullable<System.DateTime> s_CancelTime { get; set; }
        public Nullable<int> s_CancelStaffId { get; set; }
    }
}
