//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThumbsUpTable
    {
        public int t_Id { get; set; }
        public Nullable<int> t_Type { get; set; }
        public Nullable<int> t_UserId { get; set; }
        public Nullable<int> t_DataId { get; set; }
        public Nullable<System.DateTime> t_AddTime { get; set; }
    }
}
