//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCollectTable
    {
        public int uc_Id { get; set; }
        public int uc_User_id { get; set; }
        public int uc_Type { get; set; }
        public int uc_Collect_id { get; set; }
        public int uc_Status { get; set; }
        public System.DateTime uc_Created_at { get; set; }
    }
}
