//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessagePushTable
    {
        public int ump_Id { get; set; }
        public int ump_Type { get; set; }
        public Nullable<int> ump_Class_id { get; set; }
        public string ump_Title { get; set; }
        public string ump_Content { get; set; }
        public string ump_Data_url { get; set; }
        public int ump_Status { get; set; }
        public System.DateTime ump_Created_at { get; set; }
    }
}
