//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTable
    {
        public int w_Id { get; set; }
        public Nullable<int> w_Type { get; set; }
        public Nullable<int> w_UserId { get; set; }
        public string w_Title { get; set; }
        public string w_Tag { get; set; }
        public string w_Description { get; set; }
        public string w_Cover { get; set; }
        public string w_Picture { get; set; }
        public string w_ThumbNail { get; set; }
        public Nullable<int> w_ThumbUp { get; set; }
        public Nullable<int> w_Collection { get; set; }
        public Nullable<int> w_Evaluate { get; set; }
        public Nullable<int> w_IsRecommend { get; set; }
        public Nullable<int> w_IsNew { get; set; }
        public Nullable<int> w_Commentcount { get; set; }
        public Nullable<int> w_Sequence { get; set; }
        public Nullable<int> w_Status { get; set; }
        public Nullable<System.DateTime> w_AddTime { get; set; }
    }
}
