//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmptyConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTagMapTable
    {
        public int tm_Id { get; set; }
        public Nullable<int> tm_WorkId { get; set; }
        public Nullable<int> tm_TagId { get; set; }
    }
}
